#!/usr/bin/env python3

from controllers.slam.mono_driver_node import MonoDriver
import rclpy

def main():
    try:
        rclpy.init()
        mono_driver = MonoDriver()
        rclpy.spin(mono_driver)
        mono_driver.destroy_node()
        rclpy.shutdown()
    except (KeyboardInterrupt, rclpy.executors.ExternalShutdownException):
        rclpy.shutdown()



if __name__ == '__main__':
    main()
